// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1LKfvfLv_umqYkXHvua_xioDWof-GVwk',
    appId: '1:534678514265:web:6c73777f949324c4775f48',
    messagingSenderId: '534678514265',
    projectId: 'nagare-72c81',
    authDomain: 'nagare-72c81.firebaseapp.com',
    databaseURL: 'https://nagare-72c81-default-rtdb.firebaseio.com/',
    storageBucket: 'nagare-72c81.firebasestorage.app',
    measurementId: 'G-CLVLRBX7ZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ4N_G8ExYk3rHlCs_I_RSrW9HPEqrmgM',
    appId: '1:534678514265:android:8fdaafc23065f1d8775f48',
    messagingSenderId: '534678514265',
    projectId: 'nagare-72c81',
    databaseURL: 'https://nagare-72c81-default-rtdb.firebaseio.com',
    storageBucket: 'nagare-72c81.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALoVOnNCqd9CLDEll3dUXRICKTYvBirjk',
    appId: '1:534678514265:ios:ce7bc1b5dcc08d61775f48',
    messagingSenderId: '534678514265',
    projectId: 'nagare-72c81',
    databaseURL: 'https://nagare-72c81-default-rtdb.firebaseio.com',
    storageBucket: 'nagare-72c81.firebasestorage.app',
    iosBundleId: 'com.example.nagare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALoVOnNCqd9CLDEll3dUXRICKTYvBirjk',
    appId: '1:534678514265:ios:ce7bc1b5dcc08d61775f48',
    messagingSenderId: '534678514265',
    projectId: 'nagare-72c81',
    databaseURL: 'https://nagare-72c81-default-rtdb.firebaseio.com',
    storageBucket: 'nagare-72c81.firebasestorage.app',
    iosBundleId: 'com.example.nagare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1LKfvfLv_umqYkXHvua_xioDWof-GVwk',
    appId: '1:534678514265:web:a2c79b548731b196775f48',
    messagingSenderId: '534678514265',
    projectId: 'nagare-72c81',
    authDomain: 'nagare-72c81.firebaseapp.com',
    databaseURL: 'https://nagare-72c81-default-rtdb.firebaseio.com',
    storageBucket: 'nagare-72c81.firebasestorage.app',
    measurementId: 'G-9QWWE05JS1',
  );
}
